homeassistant:
  name: Home
  latitude: 44.4938
  longitude: 11.3387
  elevation: 65
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password 
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
#TODO  ignore: NETGEAR -- to avoid discovery og netgear router 

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook:

# Track the sun
sun:



# TODO start playlist automatically on boot
media_player:
  - platform: kodi
    host: 127.0.0.1
        
# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
