homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml

frontend:

config:

updater:

http: !include webservice_http.yaml
#discovery:

conversation:

logbook:
#sun:
#ios:

sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

mqtt: !include mqtt.yaml
media_player: !include_dir_merge_list media-players
#3dprinters: !include_dir_merge_named 3dprinters
device_tracker: !include_dir_merge_list device_trackers.yaml
group: !include_dir_merge_named  groups
automation: !include automations.yaml
script: !include scripts.yaml
camera: !include camera.yaml
#zones: !include_dir_merge_named zones
